### ISSUE TITLE
Does it work for Windows?

### ISSUE THREAD

**Issue by hlide** [zegervdv/wavedrom-ascii#2]
```
========== RESTART: C:\Users\hlide\Documents\Arduino\TZZ80\read_csv.py =========
Traceback (most recent call last):
  File "C:\Users\hlide\Documents\Arduino\TZZ80\read_csv.py", line 193, in <module>
    f.write("{}\n".format(BitfieldASCII.from_dict(
  File "C:\Users\hlide\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 66-130: character maps to <undefined>
```

Using IDLE.

**Comment by hlide** [comment]
It seems the only solution I have is to open the file in UTF-8 mode (generating a .h file). It looks like Windows does not recognize those characters if not generated from UTF-8.

**Comment by zegervdv** [comment]
Right, I hadn’t realized that python on Windows doesn’t handle UTF8 automatically. 

According to [this article](https://dev.to/methane/python-use-utf-8-mode-on-windows-212i) setting `PYTHONUTF8=1` might help?
